baedal/urls.py
from django.urls import path

from . import views

app_name = 'baedal' # namespace
urlpatterns = [
  path('', views.index, name = 'index'),
  # common
  path('signout', views.signout, name='signout'),
  
  # customer
  path('customer/signin', views.customer_signin, name='customer_signin'),
  path('customer/signup', views.customer_signup, name='customer_signup'),
  path('customer/home', views.customer_home, name='customer_home'),
  path('customer/new_order/<str:rest_name>', views.new_order, name='new_order'),
  path('customer/orders', views.customer_orders, name='customer_orders'),

  # restaurant
  path('restaurant/signin', views.restaurant_signin, name='restaurant_signin'),
  path('restaurant/signup', views.restaurant_signup, name='restaurant_signup'),
  path('restaurant/menus', views.restaurant_menus, name='restaurant_menus'),
  path('restaurant/new_menu', views.new_menu, name='new_menu'),
  path('restaurant/orders', views.restaurant_orders, name='restaurant_orders'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baedal.urls')),
]

baedal/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
    username = models.CharField(max_length=50, primary_key=True, unique=True)
    password = models.CharField(max_length=300)
    display_name = models.CharField(max_length=50)
    category = models.CharField(choices=models.TextChoices('Category', '치킨 중식 한식').choices, max_length=50)

class Customer(models.Model):
    username = models.CharField(max_length=50, primary_key=True, unique=True)
    password = models.CharField(max_length=300)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    
class Menu(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.IntegerField()

class Purchase(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.SET_NULL, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    total_price = models.IntegerField()
    status = models.CharField(choices=models.TextChoices('StatusType', '대기 접수 반려').choices, max_length=50)
    created_date = models.DateTimeField()

class PurchaseMenu(models.Model):
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    quantity = models.IntegerField()

baedal/views.py
from collections import defaultdict
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password, check_password
from django.utils import timezone
from django.db import transaction

from .models import Customer, Restaurant, Menu, Purchase, PurchaseMenu

def signin_required(usertype):
    def real_decorator(func):
        def wrapper(request, *args, **kargs):
            try:
                if request.session['usertype'] != usertype:
                    raise Exception("usertype don't match")
            except Exception as e:
                print(e)
                return redirect(f'baedal:{usertype}_signin')

            return func(request, *args, **kargs)
        return wrapper
    return real_decorator

# Create your views here.
def index(request):
    return render(request, 'baedal/index.html', {})

# =========== Common ======================
def signout(request):
    request.session.clear()
    return redirect('baedal:index')

# =========== Customer =====================
def customer_signin(request):
    context = {}
    if request.method == "POST" :
        username = request.POST.get('username') 
        password = request.POST.get('password') 
        try:
            user = Customer.objects.get(username=username)
            if not check_password(password, user.password):
                raise Exception("Passowrd doen't not match")

            # happy path
            request.session['username'] = username
            request.session['usertype'] = 'customer'
            return redirect('baedal:customer_home')
        except Exception as e:
            print(e)
            # failure: user doesn't exist or password doesn't match
            context['error'] = "ID 혹은 PW가 잘못되었습니다"

    return render(request, 'baedal/customer_signin.html', context)

def customer_signup(request):
    context = {}
    if request.method == "POST" :
        username = request.POST.get('username') 
        # happy path
        if not Customer.objects.filter(username=username):
            # store Customer to DB
            customer = Customer(
                username=username, 
                password=make_password(request.POST.get('password')), 
                phone=request.POST.get('phone'), 
                address=request.POST.get('address'), 
            )
            customer.save()

            return redirect('baedal:customer_signin')
        
        # failure: username already exist
        context['error'] = "이미 존재하는 ID입니다"

    return render(request, 'baedal/customer_signup.html', context)

@signin_required('customer')
def customer_home(request):
    context = {}
    
    restaurants = Restaurant.objects.all()
    cat_rests = defaultdict(list)
    for rest in restaurants:
        cat_rests[rest.category].append(rest)
    context['cat_rests'] = dict(cat_rests)
    print(cat_rests)

    return render(request, 'baedal/customer_home.html', context)

@signin_required('customer')
def new_order(request, rest_name):
    context = {}
    try:
        rest = Restaurant.objects.get(username=rest_name)
        menus = Menu.objects.filter(restaurant=rest)
        context['rest_display_name'] = rest.display_name
        context['menus'] = menus

        if request.method == 'POST':
            order = {}
            for menu in menus:
                quantity = request.POST.get(f'{menu.id}_quantity')
                if not quantity:
                    continue
                quantity = int(quantity)
                if quantity <= 0:
                    raise Exception("invalid quantity")
                order[menu.id] = (menu.name, menu.price, quantity)
            
            if not order:
                raise Exception("empty order")

            total_price = sum(price*quantity for _, price, quantity in order.values())
            
            # save to DB
            customer = Customer(username=request.session['username'])
            with transaction.atomic():
                purchase = Purchase(
                    restaurant=rest, 
                    customer=customer,
                    total_price=total_price, 
                    status='대기', 
                    created_date=timezone.now()
                )
                purchase.save()
                for name, price, quantity in order.values():
                    purchaseMenu = PurchaseMenu(
                        purchase=purchase, 
                        name = name, 
                        price = price, 
                        quantity = quantity
                    )
                    purchaseMenu.save()

            return redirect('baedal:customer_orders')
    except Exception as e:
        context['error'] = "주문 중 에러가 발생했습니다"
        print(e)
    
    return render(request, 'baedal/new_order.html', context)

@signin_required('customer')
def customer_orders(request):
    context = {}
    
    try:
        purchases = Purchase.objects.filter(customer=request.session['username']).order_by('-created_date')
        purchases = [{'created_date': purchase.created_date, 
                      'restaurant':purchase.restaurant, 
                      'total_price': purchase.total_price,
                      'status': purchase.status,
                      'menus': PurchaseMenu.objects.filter(purchase=purchase)} 
                      for purchase in purchases]

        context['purchases'] = purchases
    except Exception as e:
        print(e)
        context['error'] = '주문내역을 불러오는 도중 에러가 발생했습니다'

    return render(request, 'baedal/customer_orders.html', context)
# ============================================

# =========== Restaurant =====================
def restaurant_signin(request):
    context = {}
    if request.method == "POST" :
        username = request.POST.get('username') 
        password = request.POST.get('password') 
        try:
            user = Restaurant.objects.get(username=username)
            if not check_password(password, user.password):
                raise Exception("Passowrd doen't not match")

            # happy path
            request.session['username'] = username
            request.session['usertype'] = 'restaurant'
            return redirect('baedal:restaurant_menus')
        except Exception as e:
            print(e)
            # failure: user doesn't exist or password doesn't match
            context['error'] = "ID 혹은 PW가 잘못되었습니다"

    return render(request, 'baedal/restaurant_signin.html', context)

def restaurant_signup(request):
    context = {}
    categories = [cat for cat, _ in Restaurant.category.field.choices]
    context['categories'] = categories

    if request.method == "POST" :
        username = request.POST.get('username') 
        # happy path
        if not Restaurant.objects.filter(username=username):
            # store Customer to DB
            customer = Restaurant(
                username=username, 
                password=make_password(request.POST.get('password')), 
                display_name=request.POST.get('display_name'), 
                category=request.POST.get('category'), 
            )
            customer.save()

            return redirect('baedal:restaurant_signin')
        
        # failure: username already exist
        context['error'] = "이미 존재하는 ID입니다"

    return render(request, 'baedal/restaurant_signup.html', context)

@signin_required('restaurant')
def restaurant_menus(request):
    context = {}
    username = request.session['username']
    
    try:
        restaurant = Restaurant.objects.get(username=username)
        menus = Menu.objects.filter(restaurant=restaurant)
        context['menus'] = menus
    except Exception as e:
        print(e)
        context['menus'] = []

    return render(request, 'baedal/restaurant_menus.html', context)

@signin_required('restaurant')
def new_menu(request):
    context = {}
    username = request.session['username']
    
    if request.method == 'POST':
        try:
            restaurant = Restaurant.objects.get(username=username)
            menu = Menu(
                restaurant=restaurant, 
                name=request.POST.get('name'), 
                price=request.POST.get('price')
            )
            menu.save()
        except Exception as e:
            print(e)
        return redirect('baedal:restaurant_menus')
    
    return render(request, 'baedal/new_menu.html', context)

@signin_required('restaurant')
def restaurant_orders(request):
    context = {}
    if request.method == 'POST':
        try:
            purchase_id = request.POST.get('purchase_id')
            purchase = Purchase.objects.get(id=purchase_id)
            purchase.status = request.POST.get('status')
            purchase.save()
            return redirect(request.path)
        except Exception as e:
            context['error'] = "접수/반려 도중 에러가 발생 했습니다"
            print(e)
    
    try:
        purchases = Purchase.objects.filter(restaurant=request.session['username']).order_by('-created_date')
        purchases = [{'id': purchase.id,
                      'created_date': purchase.created_date, 
                      'customer':purchase.customer, 
                      'total_price': purchase.total_price,
                      'status': purchase.status,
                      'menus': PurchaseMenu.objects.filter(purchase=purchase)} 
                      for purchase in purchases]

        context['purchases'] = purchases

    except Exception as e:
        print(e)
        context['error'] = "주문내역을 불러오는 도중 에러가 발생했습니다"

    return render(request, 'baedal/restaurant_orders.html', context)
# ============================================

baedal/templates/baedal/customer_home.html
{% include 'baedal/customer_navbar.html' %}
<h1>홈</h1>

{% for cat, rests in cat_rests.items %}
<div>
  <h3>{{cat}}</h3>
  <ul>
    {% for rest in rests %}
    <li>
      <a href="{% url 'baedal:new_order' rest_name=rest.username %}"
        >{{rest.display_name}}</a
      >
    </li>
    {% endfor %}
  </ul>
</div>
{% endfor %}

baedal/templates/baedal/customer_navbar.html
{% extends 'baedal/navbar.html' %} {% block nav_menu %}
<li><a href="{% url 'baedal:customer_home' %}">홈</a></li>
<li><a href="{% url 'baedal:customer_orders' %}">주문내역</a></li>
{% endblock %}

baedal/templates/baedal/customer_orders.html
{% include 'baedal/customer_navbar.html' %}
<h1>주문내역</h1>
{% if error %}
<p><strong>{{error}}</strong></p>
{% endif %} {% for purchase in purchases %}
<div style="border: 1px solid black">
  <h4>{{purchase.restaurant.display_name}}</h4>
  <p>{{purchase.created_date}}</p>
  <p>상태: {{purchase.status}}</p>
  <p>총액: {{purchase.total_price}}</p>
  {{menus}}
  <ul>
    {% for menu in purchase.menus %}
    <li>{{menu.name}}: {{menu.quantity}} x {{menu.price}}</li>
    {% endfor %}
  </ul>
</div>
{% endfor %}

baedal/templates/baedal/customer_signin.html
<h1>로그인(고객용)</h1>
{% if error %}
<strong>{{error}}</strong>
{% endif %}
<form method="POST">
  <fieldset>
    {% csrf_token %}
    <label for="username">ID:</label>
    <input id="username" type="text" name="username" />
    <br />
    <label for="password">PW:</label>
    <input id="password" type="password" name="password" />
    <br />
    <input type="submit" value="로그인" />
  </fieldset>
</form>

<p>
  회원이 아니신가요?
  <a href="{% url 'baedal:customer_signup' %}">회원가입으로</a>
</p>
<p>
  음식점 사장님이신가요?
  <a href="{% url 'baedal:restaurant_signin' %}">음식점용 로그인으로</a>
</p>

baedal/templates/baedal/customer_signup.html
<h1>회원가입(고객용)</h1>
{% if error %}
<strong>{{error}}</strong>
{% endif %}
<form method="POST">
  <fieldset>
    {% csrf_token %}
    <label for="username">ID:</label>
    <input id="username" type="text" name="username" />
    <br />
    <label for="password">PW:</label>
    <input id="password" type="password" name="password" />
    <br />
    <label for="phone">전호번호</label>
    <input id="phone" type="text" name="phone" />
    <br />
    <label for="address">주소</label>
    <input id="address" type="text" name="address" />
    <br />
    <input type="submit" value="회원가입" />
  </fieldset>
</form>

<p>
  이미 회원이신가요?
  <a href="{% url 'baedal:customer_signin' %}">로그인으로</a>
</p>

baedal/templates/baedal/index.html
<h1>환영합니다</h1>
<a href="{% url 'baedal:customer_signin' %}">고객으로 로그인</a>
<a href="{% url 'baedal:restaurant_signin' %}">음식점으로 로그인</a>

baedal/templates/baedal/navbar.html
<nav>
  <ul>
    {% block nav_menu %} {% endblock %}
  </ul>
  <a href="{% url 'baedal:signout' %}">로그아웃</a>
</nav>

baedal/templates/baedal/new_menu.html
<a href="{% url 'baedal:restaurant_menus' %}">돌아가기</a>
<form method="POST">
  <fieldset>
    {% csrf_token %}
    <label for="name">메뉴명</label>
    <input id="name" type="text" name="name" />
    <br />
    <label for="price">가격</label>
    <input id="price" type="number" name="price" />
    <br />
    <input type="submit" value="완료" />
  </fieldset>
</form>

baedal/templates/baedal/new_order.html
<a href="{% url 'baedal:customer_home' %}">돌아가기</a>
<h1>{{rest_display_name}}</h1>
<p><strong>{{ error }}</strong></p>
<form method="POST">
  {% csrf_token %} {% for menu in menus %}
  <fieldset name="{{menu.name}}">
    <h4>{{menu.name}}</h4>
    <p>가격: {{menu.price}}</p>
    <label>수량: </label>
    <input type="number" name="{{menu.id}}_quantity" />
  </fieldset>
  {% endfor %}
  <input type="submit" value="주문" />
</form>

baedal/templates/baedal/restaurant_menus.html
{% include 'baedal/restaurant_navbar.html' %}
<h1>메뉴관리</h1>

<a href="{% url 'baedal:new_menu' %}">메뉴 추가</a>

{% for menu in menus %}
<div>
  <form>
    <fieldset>
      <p>{{menu.name}}</p>
      <p>{{menu.price}}</p>
    </fieldset>
  </form>
</div>
{% endfor %}

baedal/templates/baedal/restaurant_navbar.html
{% extends 'baedal/navbar.html' %} {% block nav_menu %}
<li><a href="{% url 'baedal:restaurant_menus' %}">메뉴관리</a></li>
<li><a href="{% url 'baedal:restaurant_orders' %}">주문관리</a></li>
{% endblock %}

baedal/templates/baedal/restaurant_orders.html
{% include 'baedal/restaurant_navbar.html' %}
<h1>주문관리</h1>
{% if error %}
<p><strong>{{error}}</strong></p>
{% endif %} {% for purchase in purchases %}
<form method="POST">
  {% csrf_token %}
  <fieldset>
    <h4>고객명: {{purchase.customer.username}}</h4>
    <p>{{purchase.created_date}}</p>
    <p>상태: {{purchase.status}}</p>
    <p>전화번호: {{purchase.customer.phone}}</p>
    <p>주소: {{purchase.customer.address}}</p>
    <p>총액: {{purchase.total_price}}</p>
    {{menus}}
    <ul>
      {% for menu in purchase.menus %}
      <li>{{menu.name}}: {{menu.quantity}} x {{menu.price}}</li>
      {% endfor %}
    </ul>
    {% if purchase.status == "대기" %}
    <input type="hidden" name="purchase_id" value="{{purchase.id}}" />
    <input type="radio" name="status" id="accept" value="접수" checked />
    <label for="accept">접수</label>
    <input type="radio" name="status" id="reject" value="반려" />
    <label for="reject">반려</label>
    <input type="submit" value="확인" />
    {% endif %}
  </fieldset>
</form>
{% endfor %}

baedal/templates/baedal/restaurant_signin.html
<h1>로그인(음식점용)</h1>
{% if error %}
<strong>{{error}}</strong>
{% endif %}
<form method="POST">
  <fieldset>
    {% csrf_token %}
    <label for="username">ID:</label>
    <input id="username" type="text" name="username" />
    <br />
    <label for="password">PW:</label>
    <input id="password" type="password" name="password" />
    <br />
    <input type="submit" value="로그인" />
  </fieldset>
</form>

<p>
  회원이 아니신가요?
  <a href="{% url 'baedal:restaurant_signup' %}">회원가입으로</a>
</p>
<p>
  일반 고객이신가요?
  <a href="{% url 'baedal:customer_signin' %}">고객용 로그인으로</a>
</p>

baedal/templates/baedal/restaurant_signup.html
<h1>회원가입(음식점용)</h1>
{% if error %}
<strong>{{error}}</strong>
{% endif %}
<form method="POST">
  <fieldset>
    {% csrf_token %}
    <label for="username">ID:</label>
    <input id="username" type="text" name="username" />
    <br />
    <label for="password">PW:</label>
    <input id="password" type="password" name="password" />
    <br />
    <label for="display_name">음식점명</label>
    <input id="display_name" type="text" name="display_name" />
    <br />
    <label for="category">카테고리</label>
    <select id="category" name="category">
      {% for cat in categories %}
      <option value="{{cat}}">{{cat}}</option>
      {% endfor %}
    </select>
    <br />
    <input type="submit" value="회원가입" />
  </fieldset>
</form>

<p>
  이미 회원이신가요?
  <a href="{% url 'baedal:restaurant_signin' %}">로그인으로</a>
</p>